before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/main.go
    binary: c3tsyncer
archives:
  - replacements:
      386: i386
      amd64: x86_64
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
