name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

#    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
#
#    # Run steps on a matrix of 4 arch/distro combinations
#    strategy:
#      matrix:
#        include:
#          - arch: aarch64
#            distro: ubuntu-latest
#          - arch: amd64
#            distro: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64,arm'
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Docker login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER_ADDRESS }}
          username: ${{ secrets.REGISTRY_USER_NAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.x
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
